site_name: Git Workshop BY IEDF.in & GrandAppStudio.in

theme: readthedocs

pages:
- [index.md, Home]
- [motive.md, Motivation]
- [history.md, History]
- [distributed.md, Distributed Version Control]
- [uniqueness.md, Uniqueness]
- [install.md, Installation]
- [add-git-path.md, Adding GIT DIRECTORY TO Windows PATH]
- [gitgui.md, GUI Tools For GIT]
- [initaddcommit.md, Getting Started]
- [initaddcommit_ex_1.md, Exercise on Getting Started]
- [statuslog.md, Status & Log]
- [statuslog_ex_1.md, Exercise on Status & Log]
- [checkoutrevertreset.md, Undoing Changes Safely!]
- [checkoutrevertreset_ex_1.md, Exercise on Undoing Changes Safely!]
- [branch.md, Branching Merging]
- [workflows.md, Git Workflows]
- [featureflow.md, Feature Development]
- [ref.md, References]
- [todo.md, Todo]